server {
    listen 8080;
    server_name localhost;

    # Directorio raíz del activo digital
    root /usr/share/nginx/html;
    index index.html;

    # Seguridad: Deshabilitar firma de versión
    server_tokens off;

    # Compresión para optimizar red en Soyapango
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché para recursos estáticos (Optimización FinOps)
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Cabeceras de seguridad fundamentales
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
}